name: sem
channels:
  - conda-forge
  - defaults
dependencies:
  - python=2.7
  - anaconda
  - seaborn
  - ipywidgets
  - tqdm
  - scikit-learn
  - pip:
      - tensorflow
      - keras
      - edward
